### ISSUE TITLE
Seems broke already

### ISSUE THREAD

**Issue by kodifiretvsticks** [Novalys/PokemonGo-Bot-SimpleGUI#4] opened 2016-07-22 04:42 UTC
I'm getting an error after running the compiled version.

The error says "Please allow a few seconds for the pending tasks to complete"
This occurs after logging in and then clicking "Start Farming".

In the log box it starts with "Object reference not set to an instance of an object."

**Comment by Novalys** [comment] 2016-07-22 04:50
Are you logging with PTC or Google Login?

**Comment by kodifiretvsticks** [comment] 2016-07-22 04:55
PTC. So I did a clean compile (unzipped again and just compiled after modifying the app.config files for my location and acct info), now I get it to start, it finds 1 pokestop and farms it, then moves to the second one and again it fails, same exact error pops up with a confirm button and in the log

**Comment by Novalys** [comment] 2016-07-22 05:02
Could you share your location? The one I'm using has like 140 pokestops, I'll check if it's something related with the bot not finding a next pokestop.

**Comment by kodifiretvsticks** [comment] 2016-07-22 05:05
32.747102 - lat
-117.252595 - long

**Comment by Novalys** [comment] 2016-07-22 05:16
Well I soft banned my account because of the fast location changing but still, it's finding 57 pokestops for your location? By the way, the location needs to be set in the:

PokemonGo.RocketAPI.GUI\UserSettings.settings no in the App.config

Could you try to change the settings for your location there, login with PTC and hit Start Farming to see if you get the same output as me? 

![image](https://cloud.githubusercontent.com/assets/368854/17047232/d5faf15e-4f98-11e6-8ced-2877074316c9.png)

**Comment by kodifiretvsticks** [comment] 2016-07-22 05:22
Yeah, so I started over, just modded that file you said. Now it's back to crashing after pressing "Start Farming". Very weird

**Comment by Novalys** [comment] 2016-07-22 05:25
It is indeed... I'm currently including some of the fixes that were pushed today to the Rocket API. If you want tomorrow I'll create another release with those, hopefully it will fix your problem?

**Comment by kodifiretvsticks** [comment] 2016-07-22 05:25
Hopefully so, thanks for the decent minimal gui though. Can't wait til it works for me.

**Comment by kodifiretvsticks** [comment] 2016-07-22 05:36
Heads up, tested across 3 different computers aswell to try to break down where it crashes, if it crashes on other machines.

It does still, same symptoms. All 3 pc's running Windows 10

**Comment by Novalys** [comment] 2016-07-22 05:44
OK I just pushed the latest fixes from the Pokemon Go Rocket API, try to pull that code and see if it works for you, but it seems like a environment issue for your computer. I'm going to try it in another computer to see if I can reproduce the problem and find the root cause.

**Comment by kodifiretvsticks** [comment] 2016-07-22 05:59
still the same error. tried again across 3 pc's.

**Comment by Novalys** [comment] 2016-07-22 06:02
Do you mind sending me a picture of the application after entering your credentials?

**Comment by kodifiretvsticks** [comment] 2016-07-22 06:09
This is right after login and clicking "Start Farming"
https://gyazo.com/5d5bead40348a37a612df716e8167e01

After 10 secs it pops up this button
https://gyazo.com/0308295bdc60cb7b8f971676b6afb3d9

**Comment by kodifiretvsticks** [comment] 2016-07-22 06:15
Working now on one of my accounts. I figured it had to do with my bag being overfull.

I had 450/350 items in my bag. Had to delete alot of them via my phone, then I can login with your app and continue farming.

So maybe you're program can also auto-clean your bag to keep it at it's limit or under so it doesn't crash on others like it just did for me?

:)

**Comment by Novalys** [comment] 2016-07-22 06:17
Awesome find! lol I was running out of ideas, I will create a fix for this so it empties the bag before attempting to farm.  Thanks a lot for the patience!

**Comment by kodifiretvsticks** [comment] 2016-07-22 06:18
I love finding the bugs and helping out, so this will make it better for the rest of your users.

**Closed** 2016-07-22 06:19 UTC
Labels: bug

**Comment by kodifiretvsticks** [comment] 2016-07-22 06:34
***This is closed still - Adding a note***
The app also crashes if you are maxed out on pokemon you are carrying, other account had 250/250 and was crashing it too until I candied them.

**Comment by Novalys** [comment] 2016-07-22 06:59
Yeah I imagined it would do that also for Pokemon's, it's going to be fixed tomorrow, thanks anyway for the report :smile:
