### ISSUE TITLE
Google Auth?

### ISSUE THREAD

**Issue by fafal** [Novalys/PokemonGo-Bot-SimpleGUI#157] opened 2016-07-29 03:52 UTC
Feel free to move this post/delete it if thats a duplicate :(

Any ideas what to do with that? I can log in but after i press START there is somethin like that ~after 30-40s
![123](https://cloud.githubusercontent.com/assets/7698889/17237285/8a78e980-5550-11e6-82f8-ce6ed5377d32.jpg)

**Comment by yupdon** [comment] 2016-07-29 03:58
Confirmed: I'm seeing the same thing I'll see if i can dig into it.

**Comment by yupdon** [comment] 2016-07-29 04:27
So far so good, seems like its the rocket API issue due to API changes, everyone else seems to have these issues also.

FortDetailsResponse fortInfo = null;
                try { 
                 fortInfo = await _client.GetFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

                }
                catch (Exception ex)
                {
                    var p = ex.Message; //Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
                }

You should see the same err in the startup, after setting your location.

**Comment by yupdon** [comment] 2016-07-29 04:47
Hey so I have a temp fix going. I've added in a 500ms delay between each of the await calls (outgoing to the API) within ExecuteFarmingPokestopsAndPokemons() and any sub Functions. (ITS NOT a Pretty fix)

Seems to be working now, (with delay of course)... but better than nothing.

@Novalys Should I add the changed code below? or is this enough to get a hotfix patch going until the api works properly?

**Comment by Dbarr74** [comment] 2016-07-29 05:06
hey Yupdon, what did you change? Been trying some of the other fixes posted a few hours ago, but keeps giving me google token failure.

**Comment by yupdon** [comment] 2016-07-29 05:22
Here are the functions I altered to get it working without exceptions: All are located in mainForm.cs you can replace the code (locally ofcourse) with this. - again not Pretty fixes, and shouldn't get checked in. (has some debug code I was using also)

              private async void MainForm_Load(object sender, EventArgs e)
                 {
                try
               {
                // Setup Console
                console = new ConsoleForm();
                console.TopMost = true;
                console.StartPosition = FormStartPosition.Manual;                
                console.Location = new System.Drawing.Point((Screen.PrimaryScreen.Bounds.Width / 2) - 530, (Screen.PrimaryScreen.Bounds.Height / 2) + 310);                

                // Start Loading
                StartLogger();
                CleanUp();

                // Begin Process
                await DisplayLoginWindow();                
                DisplayPositionSelector();
                await Task.Delay(500);
                await GetCurrentPlayerInformation();
                await Task.Delay(500);
                await PreflightCheck();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                Logger.Write(ex.Message);
            }
        }


     public async Task GetCurrentPlayerInformation()
        {
            var playerName = _profile.Profile.Username ?? "";
            await Task.Delay(500);
            var playerStats = await _inventory.GetPlayerStats();
            var playerStat = playerStats.FirstOrDefault();
            if (playerStat != null)
            {
                var xpDifference = GetXpDiff(playerStat.Level);                
                lbName.Text = playerName;
                lbLevel.Text = $"Lv {playerStat.Level}";
                lbExperience.Text = $"{playerStat.Experience - playerStat.PrevLevelXp - xpDifference}/{playerStat.NextLevelXp - playerStat.PrevLevelXp - xpDifference} XP";

                expProgressBar.Minimum = 1;
                expProgressBar.Maximum = (int)(playerStat.NextLevelXp - playerStat.PrevLevelXp - xpDifference);
                expProgressBar.Value = (int)(playerStat.Experience - playerStat.PrevLevelXp - xpDifference);                
            }

            // Get Pokemons and Inventory
            await Task.Delay(500);
            var myItems = await _inventory.GetItems();
            await Task.Delay(500);
            var myPokemons = await _inventory.GetPokemons();

            // Write to Console
            var items = myItems as IList<Item> ?? myItems.ToList();
            boxInventoryCount.Text = $"{items.Select(i => i.Count).Sum()}/350";
            boxPokemonCount.Text = $"{myPokemons.Count()}/250";
            boxLuckyEggsCount.Text = (items.FirstOrDefault(p => (ItemId)p.Item_ == ItemId.ItemLuckyEgg)?.Count ?? 0).ToString();
            boxIncencesCount.Text = (items.FirstOrDefault(p => (ItemId)p.Item_ == ItemId.ItemIncenseOrdinary)?.Count ?? 0).ToString();            
        }


      private async Task ExecuteFarmingPokestopsAndPokemons()
        {
            GetMapObjectsResponse mapObjects = null;
            try
            {
                await Task.Delay(500);
                mapObjects = await _client.GetMapObjects();

            }
            catch (Exception ex)
            {
                var p = ex.Message;
            }
            IEnumerable<FortData> pokeStops = null;
            try
            {
                await Task.Delay(500);
                pokeStops = mapObjects.MapCells.SelectMany(i => i.Forts).Where(i => i.Type == FortType.Checkpoint && i.CooldownCompleteTimestampMs < DateTime.UtcNow.ToUnixTime());

            }
            catch (Exception ex)
            {
                var p = ex.Message;
            }
            IList<FortData> fortDatas = null;
            int count = 1;
            try
            {
                await Task.Delay(500);
                fortDatas = pokeStops as IList<FortData> ?? pokeStops.ToList();
                _pokestopsCount = fortDatas.Count<FortData>();

            }
            catch (Exception ex)
            {
                var p = ex.Message;
            }

            foreach (var pokeStop in fortDatas)
            {
                try
                {
                    await Task.Delay(500);
                    var update = await _client.UpdatePlayerLocation(pokeStop.Latitude, pokeStop.Longitude, _settings.DefaultAltitude); // Redundant?

                }
                catch (Exception ex)
                {
                    var p = ex.Message;
                }

                try
                {
                    await Task.Delay(500);
                    UpdateMap(pokeStop.Latitude, pokeStop.Longitude);

                }
                catch (Exception ex)
                {
                    var p = ex.Message;
                }
                FortDetailsResponse fortInfo = null;
                try
                {
                    await Task.Delay(500);
                    fortInfo = await _client.GetFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

                }
                catch (Exception ex)
                {
                    var p = ex.Message;
                }

                boxPokestopName.Text = fortInfo.Name;
                boxPokestopInit.Text = count.ToString();
                boxPokestopCount.Text = _pokestopsCount.ToString();
                count++;

                FortSearchResponse fortSearch = null;
                try
                {
                    await Task.Delay(500);
                    fortSearch = await _client.SearchFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

                }
                catch (Exception ex)
                {
                    var p = ex.Message;
                }

                Logger.Write($"Loot -> Gems: { fortSearch.GemsAwarded}, Eggs: {fortSearch.PokemonDataEgg} Items: {StringUtils.GetSummedFriendlyNameOfItemAwardList(fortSearch.ItemsAwarded)}");
                Logger.Write("Gained " + fortSearch.ExperienceAwarded + " XP.");

                // Experience Counter
                _totalExperience += fortSearch.ExperienceAwarded;

                try
                {
                    await Task.Delay(500);
                    await GetCurrentPlayerInformation();

                }
                catch (Exception ex)
                {
                    var p = ex.Message;
                }

                Logger.Write("Attempting to Capture Nearby Pokemons.");
                try
                {
                    await Task.Delay(500);
                    await ExecuteCatchAllNearbyPokemons();
                }
                catch (Exception ex)
                {
                    var p = ex.Message;
                }

                if (!_isFarmingActive)
                {
                    await Task.Delay(500);
                    Logger.Write("Stopping Farming Pokestops.");
                    return;
                }

                Logger.Write("Waiting before moving to the next Pokestop.");
                await Task.Delay(GUISettings.Default.pokestopDelay * 1000);
            }
        }


      private async Task ExecuteCatchAllNearbyPokemons()
        {
            await Task.Delay(500);
            var mapObjects = await _client.GetMapObjects();

            await Task.Delay(500);
            var pokemons = mapObjects.MapCells.SelectMany(i => i.CatchablePokemons);

            var mapPokemons = pokemons as IList<MapPokemon> ?? pokemons.ToList();
            Logger.Write("Found " + mapPokemons.Count<MapPokemon>() + " Pokemons in the area.");
            foreach (var pokemon in mapPokemons)
            {
                await Task.Delay(500);
                var update = await _client.UpdatePlayerLocation(pokemon.Latitude, pokemon.Longitude, _settings.DefaultAltitude); // Redundant?
                await Task.Delay(500);
                var encounterPokemonResponse = await _client.EncounterPokemon(pokemon.EncounterId, pokemon.SpawnpointId);
                var pokemonCp = encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp;
                var pokemonIv = Logic.Logic.CalculatePokemonPerfection(encounterPokemonResponse?.WildPokemon?.PokemonData).ToString("0.00") + "%";
                await Task.Delay(500);
                var pokeball = await GetBestBall(pokemonCp);

                Logger.Write($"Fighting {pokemon.PokemonId} with Capture Probability of {(encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First())*100:0.0}%");

                boxPokemonName.Text = pokemon.PokemonId.ToString();
                boxPokemonCaughtProb.Text = (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() * 100).ToString() + @"%";                

                CatchPokemonResponse caughtPokemonResponse;
                do
                {
                    if (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() < (GUISettings.Default.minBerry / 100))
                    {
                        await Task.Delay(500);
                        await UseBerry(pokemon.EncounterId, pokemon.SpawnpointId);
                    }

                    await Task.Delay(500);
                    caughtPokemonResponse = await _client.CatchPokemon(pokemon.EncounterId, pokemon.SpawnpointId, pokemon.Latitude, pokemon.Longitude, pokeball);
                    await Task.Delay(2000);
                }
                while (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchMissed);

                Logger.Write(caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess ? $"We caught a {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} using a {pokeball}" : $"{pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} got away while using a {pokeball}..");

                if (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess)
                {
                    // Calculate Experience
                    int fightExperience = 0;
                    foreach (int exp in caughtPokemonResponse.Scores.Xp)
                        fightExperience += exp;
                    _totalExperience += fightExperience;
                    Logger.Write("Gained " + fightExperience + " XP.");
                    _pokemonCaughtCount++;

                    // Add Row to the DataGrid
                    dGrid.Rows.Insert(0, "Captured", pokemon.PokemonId.ToString(), encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp, pokemonIv);
                }
                else
                {
                    // Add Row to the DataGrid
                    dGrid.Rows.Insert(0, "Ran Away", pokemon.PokemonId.ToString(), encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp, pokemonIv);
                }

                boxPokemonName.Clear();
                boxPokemonCaughtProb.Clear();

                await Task.Delay(500);
                await GetCurrentPlayerInformation();

                if (!_isFarmingActive)
                {
                    Logger.Write("Stopping Farming Pokemons.");
                    return;
                }

                Logger.Write("Waiting before moving to the next Pokemon.");
                await Task.Delay(GUISettings.Default.pokemonDelay * 1000);
            }
        }

**Comment by yupdon** [comment] 2016-07-29 05:24
As a bonus - adding the delay also got the transfer duplicates working without throwing exceptions.

**Comment by Dbarr74** [comment] 2016-07-29 06:18
sadly, wasn't able to get it to working for me, keeps giving me the same loop, tried copying this too, bu didn't work.

**Comment by yupdon** [comment] 2016-07-29 06:21
Then your missing a subFunction, as mentioned above. If they all have the wait on it you won't get the error.

**Comment by sayiid** [comment] 2016-07-29 06:23
Not working. Maybe basic guide what i need change?

**Comment by Dbarr74** [comment] 2016-07-29 06:28
Sadly Yupdon, I don't know how to recombine the confiles back into the exe, I just know how to edit and update the code.

**Comment by Bloodipwn** [comment] 2016-07-29 12:44
Yupdon your temporarily fix is working, atleast for me. 
It seems like the program is sending packages to quickly or something like that.

**Comment by yupdon** [comment] 2016-07-29 14:13
@Dbarr74 and @sayiid You just need to copy the functions and Replace functions that are currently in the system until ticket #160 or a better solution presents itself. Then build it in Release or just run it in debug mode... This worked all night long for me.

@Bloodipwn That - exactly that.

**Comment by R1NZLR** [comment] 2016-07-29 19:54
@Dbarr74 I compiled with @yupdon edits. And built as release. Its working beautifully.

https://www.sendspace.com/file/dtadm2

**Comment by Dbarr74** [comment] 2016-07-29 20:15
@R1NZLR You sir are amazing, i tried to use some programs this morning to compile everything, but sadly the last programming I really did was html and java back in high school 10 years ago. lol

I really should get back into it.

**Comment by R1NZLR** [comment] 2016-07-29 20:39
I mainly program in swift, but its close enought to c# that I can figure it out. Im glad I could help

**Comment by adamgyongyosi** [comment] 2016-07-30 05:17
@Novalys canyou fix this in day?

**Comment by fafal** [comment] 2016-07-30 05:30
In version 1.2 works without problem

**Comment by adamgyongyosi** [comment] 2016-07-30 05:33
![image](https://cloud.githubusercontent.com/assets/5511526/17268347/f464c184-5627-11e6-9be2-aebd6a28ad2d.png)

**Closed** 2016-08-02 08:04 UTC
