### ISSUE TITLE
Unable to evolve pokemon with candies or transfer duplicates

### ISSUE THREAD

**Issue by rlogiurato** [Novalys/PokemonGo-Bot-SimpleGUI#211] opened 2016-08-01 16:08 UTC
I know I have enough candies and duplicates, but upon using these commands, the console says:

selecting pokemon to evolve
evolving finished
selecting pokemon to transfer
transfer finished

and in the box that shows actions it shows all the pokemon in my box and next to it 'not transferred'

**Comment by yupdon** [comment] 2016-08-01 16:20
are all your pokemon above 1000cp and 85% (default iv %)?

**Comment by rlogiurato** [comment] 2016-08-01 16:25
regarding transfer - no I changed mine to 100cp and 50% IV and it would not transfer pokemon that didnt meet the requirements
regarding evolve - yes i am talking about menu evolve and transfer not auto button in  settings

**Comment by rlogiurato** [comment] 2016-08-01 16:26
im not sure what just happened but i tried it again and it started working? so i guess problem solved thanks anyway

**Comment by yupdon** [comment] 2016-08-01 17:38
Np, was about to say that I can't reproduce it, next time I recommend debugging it, to catch the anomaly.  - Cheers

**Comment by Novalys** [comment] 2016-08-02 07:49
If it says "Not Transferred" is because your settings (Check the settings inside the app) for CP and IV are preventing the transfer.

**Closed by Novalys** 2016-08-02 07:49 UTC
